inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.7
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - rubyrag.gemspec